site_name: VanBUG
docs_dir: src
theme:
  name: material
  logo: images/logo.light.svg
  favicon: images/logo.svg
  features:
    - navigation.tabs
    - navigation.top
    - navigation.tabs.sticky
    - navigation.instant
    - toc.integrate
site_dir: dist
markdown_extensions:
  - codehilite
  - admonition
  - pymdownx.inlinehilite
  - pymdownx.extra
  - pymdownx.blocks.html

  - pymdownx.snippets:
      check_paths: True
      base_path: .
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - attr_list
  - pymdownx.arithmatex:
      generic: true
  - toc:
      permalink: true
extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://platform.twitter.com/widgets.js
extra_css:
- styles/image-list.css
- styles/timeline.css
- styles/palette.css
- styles/general.css
- styles/image-gallery.css
plugins:
  - awesome-pages
  - search
  - include-markdown
  - mkdocs-video
  - redirects:
      redirect_maps:
        2022/career-panel/index.md: archive/2022/2022-05-19.md
        2022/carl-de-boer/index.md: archive/2022/2022-04-20.md
        2022/aline-talhouk/index.md: archive/2022/2022-03-16.md
        2022/sandrine-moreira/index.md: archive/2022/2022-02-16.md
        2022/sabah-ul-hasan/index.md: archive/2022/2022-01-19.md
        2021/3-minute-lightning-talks/index.md: archive/2021/2021-12-09.md
        2021/jesse-gillis/index.md: archive/2021/2021-11-17.md
        2021/adi-steif/index.md: archive/2021/2021-10-20.md
        2021/tao-huan/index.md: archive/2021/2021-09-22.md
        2021/jianguo-jeff-xia/index.md: archive/2021/2021-04-14.md
        2021/michael-hoffman/index.md: archive/2021/2021-03-17.md
        2021/carolina-tropini/index.md: archive/2021/2021-01-20.md
        2020/natalie-prystajecky/index.md: archive/2020/2020-12-09.md
        2020/cara-haney/index.md: archive/2020/2020-11-18.md
        2020/zamin-iqbal/index.md: archive/2020/2020-10-21.md
        2020/rayan-chikhi/index.md: archive/2020/2020-09-16.md
        2020/ibrahim-numanagic/index.md: archive/2020/2020-04-16.md
        2020/matt-pennell/index.md: archive/2020/2020-02-20.md
        2020/raymond-ng/index.md: archive/2020/2020-01-23.md
        2019/quaid-morris-2/index.md: archive/2019/2019-12-12.md
        2019/sam-aparicio/index.md: archive/2019/2019-11-28.md
        2019/derek-r-dee/index.md: archive/2019/2019-10-31.md
        2019/william-hsiao-2/index.md: archive/2019/2019-09-26.md
        2019/denise-daley/index.md: archive/2019/2019-05-09.md
        2019/anshul-kundaje/index.md: archive/2019/2019-04-11.md
        2019/jeff-joy/index.md: archive/2019/2019-03-14.md
        2018/gabriela-cohen-freue/index.md: archive/2018/2018-11-15.md
        2018/caroline-colijn/index.md: archive/2018/2018-10-11.md
        2018/melissa-haendel/index.md: archive/2018/2018-09-13.md
        2018/mike-farmulare/index.md: archive/2018/2018-05-10.md
        2018/jared-simpson/index.md: archive/2018/2018-04-12.md
        2018/faraz-hach/index.md: archive/2018/2018-02-08.md
        2018/january-11th-special-event/index.md: archive/2018/2018-01-11.md
        2017/laura-parfrey/index.md: archive/2017/2017-11-09.md
        2017/lior-pachter/index.md: archive/2017/2017-10-12.md
        2017/max-libbrecht/index.md: archive/2017/2017-09-21.md
        2017/melissa-wilson-sayres/index.md: archive/2017/2017-05-11.md
        2017/robin-dowell/index.md: archive/2017/2017-04-06.md
        2017/grace-zheng/index.md: archive/2017/2017-03-09.md
        2017/yassene-mohammed/index.md: archive/2017/2017-02-09.md
        2016/rob-beiko/index.md: archive/2016/2016-12-15.md
        2016/jonathan-carlson/index.md: archive/2016/2016-11-03.md
        2016/amee-manges/index.md: archive/2016/2016-10-12.md
        2016/martin-krzywinski/index.md: archive/2016/2016-09-15.md
        2016/elhanan-borenstein/index.md: archive/2016/2016-04-14.md
        2016/sara-mostafavi/index.md: archive/2016/2016-03-10.md
        2016/adam-phillippy/index.md: archive/2016/2016-02-11.md
        2015/how-to-become-an-entrepreneur/index.md: archive/2015/2015-12-10.md
        2015/leonid-chindelevitch/index.md: archive/2015/2015-11-05.md
        2015/tamara-munzner/index.md: archive/2015/2015-10-08.md
        2015/fiona-brinkman-2/index.md: archive/2015/2015-09-17.md
        2015/temple-smith/index.md: archive/2015/2015-05-05.md
        2015/martin-hirst/index.md: archive/2015/2015-04-09.md
        2015/c-titus-brown/index.md: archive/2015/2015-03-12.md
        2015/nick-loman/index.md: archive/2015/2015-02-12.md
        2014/dave-clarke/index.md: archive/2014/2014-10-09.md
        2014/jennifer-gardy/index.md: archive/2014/2014-09-25.md
        2014/dana-pe%e2%80%99er/index.md: archive/2014/2014-04-10.md
        2014/michel-dumontier/index.md: archive/2014/2014-03-13.md
        2014/gene-myers/index.md: archive/2014/2014-02-06.md
        2013/ryan-morin/index.md: archive/2013/2013-11-14.md
        2013/gary-van-domselaar/index.md: archive/2013/2013-10-10.md
        2013/christopher-hogue/index.md: archive/2013/2013-09-12.md
        2013/art-poon/index.md: archive/2013/2013-03-07.md
        2013/bonnie-kirkpatrick/index.md: archive/2013/2013-02-07.md
        2012/ben-raphael/index.md: archive/2012/2012-11-08.md
        2012/robert-balshaw/index.md: archive/2012/2012-10-18.md
        2012/katherine-pollard/index.md: archive/2012/2012-09-13.md
        2012/phil-bourne/index.md: archive/2011/2011-04-12.md
        2012/nathan-price/index.md: archive/2011/2011-03-08.md
        2012/william-hsiao/index.md: archive/2011/2011-02-09.md
        2011/francois-major/index.md: archive/2011/2011-12-08.md
        2011/paul-pavlidis-2/index.md: archive/2011/2011-11-17.md
        2011/inanc-birol/index.md: archive/2011/2011-10-13.md
        2011/20112012-season/index.md: archive/2011/2011-09-08.md
        2011/careers-in-bioinformatics/index.md: archive/2011/2011-04-14.md
        2011/martha-bulyk/index.md: archive/2011/2011-03-17.md
        2011/andrew-clark/index.md: archive/2011/2011-03-10.md
        2011/mathieu-blanchette/index.md: archive/2011/2011-01-20.md
        2010/todd-woodward/index.md: archive/2010/2010-12-09.md
        2010/quaid-morris/index.md: archive/2010/2010-11-10.md
        2010/steven-hallam/index.md: archive/2010/2010-10-14.md
        2010/sarah-teichmann/index.md: archive/2010/2010-09-09.md
        2010/joerg-gsponer/index.md: archive/2010/2010-04-08.md
        2010/richard-bonneau/index.md: archive/2010/2010-03-11.md
        2010/evan-eichler/index.md: archive/2010/2010-01-13.md
        2009/sohrab-shah/index.md: archive/2009/2009-11-26.md
        2009/chris-shaw/index.md: archive/2009/2009-10-08.md
        2009/rbrinkman_sept09/index.md: archive/2009/2009-09-10.md
        2009/april2009/index.md: archive/2008/2008-04-09.md
        2009/march2009/index.md: archive/2009/2009-03-12.md
        2009/february-12-2009/index.md: archive/2009/2009-02-12.md
        2009/gary_bader/index.md: archive/2009/2009-01-08.md
        2008/december2008/index.md: archive/2008/2008-12-11.md
        2008/raymond_ng/index.md: archive/2008/2008-11-13.md
        2008/william_noble/index.md: archive/2008/2008-10-09.md
        2008/david_lynn/index.md: archive/2008/2008-09-11.md
        2008/artem_cherkasov/index.md: archive/2008/2008-04-10.md
        2008/margaret-anne_storey/index.md: archive/2007/2007-03-13.md
        2008/january/index.md: archive/2007/2007-01-10.md
        2008/february/index.md: archive/2007/2007-02-13.md
        2007/john_storey/index.md: archive/2007/2007-12-13.md
        2007/eleazar_eskin/index.md: archive/2007/2007-11-08.md
        2007/jack_chen/index.md: archive/2007/2007-10-11.md
        2007/paul-pavlidis/index.md: archive/2007/2007-09-13.md
        2007/ericgreen/index.md: archive/2007/2007-04-12.md
        2007/amos-bairoch/index.md: archive/2007/2007-03-08.md
        2007/sean-eddy-2/index.md: archive/2007/2007-02-07.md
        2007/irmtraud-meyer/index.md: archive/2007/2007-01-11.md
        2006/shoshana-wodak/index.md: archive/2006/2006-12-14.md
        2006/holger-hoos/index.md: archive/2006/2006-11-09.md
        2006/ron-beavis/index.md: archive/2006/2006-10-12.md
        2006/hamid-bolouri/index.md: archive/2006/2006-09-14.md
        2006/jason-stajich/index.md: archive/2006/2006-04-13.md
        2006/raphael-gottardo/index.md: archive/2006/2006-02-09.md
        2006/ken-dill/index.md: archive/2006/2006-01-12.md
        2005/gary-stormo/index.md: archive/2005/2005-12-08.md
        2005/wayne-maddison/index.md: archive/2005/2005-11-17.md
        2005/david-wishart-the-bioinformatics-of-small-molecule/index.md: archive/2005/2005-10-13.md
        2005/win-hide/index.md: archive/2005/2005-09-08.md
        2005/christoph-w-sensen/index.md: archive/2005/2005-04-21.md
        2005/asim-siddiqui/index.md: archive/2005/2005-03-17.md
        2005/eldon-emberly/index.md: archive/2005/2005-02-10.md
        2005/isidore-rigoutsos/index.md: archive/2005/2005-01-13.md
        2004/michael-hallett/index.md: archive/2004/2004-12-15.md
        2004/mark-wilkinson/index.md: archive/2004/2004-11-18.md
        2004/chris-hogue/index.md: archive/2004/2004-10-14.md
        2004/gabor-marth/index.md: archive/2004/2004-09-09.md
        2004/jenny-bryan/index.md: archive/2004/2004-04-08.md
        2004/fiona-brinkman/index.md: archive/2004/2004-03-18.md
        2004/michael-eisen/index.md: archive/2004/2004-02-12.md
        2003/arvind-gupta/index.md: archive/2003/2003-12-11.md
        2003/paul-thomas/index.md: archive/2003/2003-11-20.md
        2003/cenk-sahinalp/index.md: archive/2003/2003-10-02.md
        2003/john-quackenbush/index.md: archive/2003/2003-09-11.md
        2003/season-end-celebration/index.md: archive/2003/2003-05-13.md
        2003/dnagenome-anniversary-celebration/index.md: archive/2003/2003-04-08.md
        2003/chris-upton/index.md: archive/2003/2003-03-13.md
        2003/ann-condon/index.md: archive/2003/2003-02-13.md
        2003/nat-goodman/index.md: archive/2003/2003-01-09.md
        2002/steven-jones/index.md: archive/2002/2002-12-12.md
        2002/lincoln-stein/index.md: archive/2002/2002-11-14.md
        2002/wyeth-w-wasserman-detection-and-analysis-of-transcriptional-control-sequences-in-the-human-genome/index.md: archive/2002/2002-10-10.md
        2002/francis-ouellette-a-human-aided-automated-pipeline-to-the-annotate-the-human-genome-work-in-progress/index.md: archive/2002/2002-09-12.md
nav:
  - Home: index.md
  - ...
extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/VanBUG_
    - icon: fontawesome/brands/github
      link: https://github.com/van-bug
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/channel/UCO_BUmZqGLx_w9-IpAj4idQ
